name: studify repository

on: workflow_dispatch

jobs:
  # setup-repo:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - run: npm install
  #     - run: node ./actions/setup-repo.js user repo
  dump: # https://stackoverflow.com/a/62805013
    runs-on: ubuntu-latest
    steps:
      - run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  render-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: render readme
        users: our action
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.7.2
        with:
          commit_message: rendered new README
          branch: ${{ github.head_ref }}
